[model]
name = Image (attachment with extras)
label = {{ this.title }}
hidden = yes
inherits = attachment-image

; cover_image, width=1/4

[fields.sort_key]
label = Sort Key
type = sort_key
width = 1/4

[fields.css_classes]
label = CSS classes
type = checkboxes
choices = highlight
width = 1/2

[fields.alttext]
label = Alt text
type = string
width = 1

[fields.caption]
label = Caption
type = html
width = 1
